spring:
  application:
    name: materialmanager

  profiles:
      active: dev
#      active: prod

  # JPA -> ?? ??
  jpa:
    show-sql: true
    # ???? jpa ???? ???? sql? ??? ????
    properties:
      # jpa ???
      hibernate:
        # ?? ?? sql ???, ????, ?? ?? ????
        format_sql: true
    # ??? ?? ??
    hibernate:
      ddl-auto: create

  # ????
  thymeleaf:
    cache: false