spring:
  application:
    name: materialmanager

  profiles:
#      active: dev
      active: prod

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
#      ddl-auto: create
      ddl-auto: update

  thymeleaf:
    cache: false